version: "3"
services:
  ums-frontend:
    build: 
      context: ./frontend
      dockerfile: ../docker/frontend.Dockerfile
    networks:
      - ums-user-facing
  ums-backend:
    build: 
      context: ./backend
      dockerfile: ../docker/backend.Dockerfile
    networks:
      - ums-user-facing
      - ums-back-office
    environment:
      UMS_DB_NAME: ums 
      UMS_DB_USERNAME: dev 
      UMS_DB_PASSWORD: devpass 
      UMS_DB_IP: maria-db
    depends_on:
      - maria-db
      - redis
    restart: always
  maria-db:
    image: mariadb:11
    environment:
      MARIADB_DATABASE: ums
      MARIADB_USER: dev
      MARIADB_PASSWORD: devpass 
      MARIADB_ROOT_PASSWORD: devpass
    networks:
      - ums-back-office
    volumes:
      - db-data:/var/lib/mysql
  ums-proxy:
    image: nginx:1.21
    ports:
      - "7887:80"
    networks:
      - ums-user-facing
    depends_on:
      - ums-frontend
      - ums-backend
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf
  redis:
    image: redis:7.2.1
    networks:
      - ums-back-office
networks:
  ums-user-facing:
  ums-back-office:
volumes:
  db-data:
    driver: local